baseURL = "https://www.noisedh.cn"
languageCode = "zh-CN"
title = "Noise导航 & 收录值得珍藏的网站"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "Noise导航"
    description   = "Noise导航 & 收录值得珍藏的网站"
    siteurl       = "./"
    about         = "./about"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://noisedh.cn"
    enablePreLoad = false		    		        # 网站完全打开前预加载的动画
    textPreLoad   = "Noise导航 & 收录珍藏的网站"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    logosPath     = "assets/images/logos"				# 网站每个导航地址logo存放地址

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-light.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-night.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bioitee-expand-light.png"
    logoExpandDark    = "assets/images/bioitee-expand-dark.png"
    logoCollapseLight = "assets/images/logo-collapse-light.png"
    logoCollapseDark  = "assets/images/logo-collapse-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '<p>本站收录值得珍藏的网站，欢迎访问使用</p>©<a href="https://noisedh.cn" target="_blank"><strong>noise导航</strong></a> '

[params.utteranc]
enable = true
repo = "rcy1314/daohang"    # 存储评论的Repo，格式为 owner/repo
issueTerm = "title"           # 表示你选择以那种方式让github issue的评论和你的文章关联可以选择默认的pathname。
theme = "github-light"        # 样式主题